/**
 * Sample product data for the Register App template.
 *
 * Images reference local assets/products/ — replace with real API data
 * in production. Mirrors the smart-terminal-design-system source set.
 */
import { ProductCardProps } from '../components/register/ProductCard';

export const SAMPLE_PRODUCTS: (ProductCardProps & { id: string })[] = [
  {
    id:            'p1',
    name:          'Yellow Leather Backpack',
    price:         '$30.00',
    originalPrice: '$35.00',
    quantity:      20,
    status:        'in-stock',
    labelColor:    '#E6A817',
    labelText:     'BAG',
  },
  {
    id:         'p2',
    name:       'Polo T-Shirt',
    price:      '',
    seeAll:     true,
    status:     'in-stock',
    labelColor: '#1976D2',
    labelText:  'POLO',
  },
  {
    id:            'p3',
    name:          'Leather Belts',
    price:         '$30.00',
    originalPrice: '$35.00',
    quantity:      5,
    status:        'low-in-stock',
    labelColor:    '#5D4037',
    labelText:     'BELT',
  },
  {
    id:         'p4',
    name:       'Travel Backpack',
    price:      '$30.00',
    quantity:   0,
    status:     'out-of-stock',
    labelColor: '#455A64',
    labelText:  'TRVL',
  },
  {
    id:         'p5',
    name:       'Flight Jacket',
    price:      '',
    seeAll:     true,
    status:     'in-stock',
    labelColor: '#37474F',
    labelText:  'JCKT',
  },
  {
    id:            'p6',
    name:          'Nike Sneakers',
    price:         '$30.00',
    originalPrice: '$35.00',
    quantity:      20,
    status:        'in-stock',
    labelColor:    '#C62828',
    labelText:     'SNKR',
  },
  {
    id:         'p7',
    name:       'Coffee Mugs',
    price:      '$35.00',
    quantity:   12,
    labelColor: '#EF6C0F',
    labelText:  'CMUGS',
    status:     'in-stock',
  },
  {
    id:         'p8',
    name:       'T-Shirt Collection',
    price:      '',
    seeAll:     true,
    status:     'in-stock',
    labelColor: '#1B5E20',
    labelText:  'TSHRT',
  },
  {
    id:            'p9',
    name:          'Brown Jacket',
    price:         '$30.00',
    originalPrice: '$35.00',
    quantity:      20,
    status:        'in-stock',
    labelColor:    '#6D4C41',
    labelText:     'BRJKT',
  },
  {
    id:         'p10',
    name:       'Leather Wallet',
    price:      '$35.00',
    quantity:   12,
    labelColor: '#8B0053',
    labelText:  'WALLE',
    status:     'in-stock',
  },
  {
    id:         'p11',
    name:       "Men's Long Sleeve Shirt",
    price:      '$30.00',
    quantity:   3,
    status:     'low-in-stock',
    labelColor: '#01579B',
    labelText:  'SLEVE',
  },
  {
    id:         'p12',
    name:       'Women Yellow Scarf',
    price:      '$35.00',
    quantity:   47,
    status:     'in-stock',
    labelColor: '#F9A825',
    labelText:  'SCARF',
  },
];
